export const base = {
  transparent: 'transparent',
  current: 'currentColor',
  black: '#000000',
  white: '#ffffff',
  brand: {
    50: '#f0f9ff',
    100: '#e0f2fe',
    200: '#bae6fd',
    300: '#7dd3fc',
    400: '#38bdf8',
    500: '#0ea5e9',
    600: '#0284c7',
    700: '#0369a1',
    800: '#075985',
    900: '#0c4a6e',
    950: '#082f49',
  },
  slate: {
    50: '#f8fafc',
    100: '#f1f5f9',
    200: '#e2e8f0',
    300: '#cbd5e1',
    400: '#94a3b8',
    500: '#64748b',
    600: '#475569',
    700: '#334155',
    800: '#1e293b',
    900: '#0f172a',
    950: '#020617',
  },
  success: '#10b981',
  'success-subtle': '#dcfce7',
  'success-dark': '#16a34a',
  error: '#ef4444',
  'error-dark': '#dc2626',
  warning: '#f59e0b',
  'warning-subtle': '#fef3c7',
  'warning-dark': '#d97706',
  info: '#3b82f6',
  'info-subtle': '#eff6ff',
  'info-dark': '#1d4ed8',
  // Action color: used for primary interactive controls (buttons, links) across the platform.
  // Diverges from brand sky palette (#0284c7). ADR required before semantic promotion.
  // Intent: interactive action. Color may change — the intent will not.
  'action': '#2563eb',
  // Inverse surface (dark slate) — used for dark-background cards in light mode (e.g. wallet card)
  'inverse-surface': '#1e293b',
  'inverse-muted': '#94a3b8',
  'inverse-subtle': '#cbd5e1',
  // Scrim / overlay
  'overlay': 'rgba(15, 23, 42, 0.6)',
};

// Semantic intent mapping directly to base primitives, independent of platform rendering tools (e.g. CSS Vars)
export const semantic = {
  light: {
    background: base.white,
    foreground: base.slate[950],
    card: base.white,
    'card-foreground': base.slate[950],
    popover: base.white,
    'popover-foreground': base.slate[950],
    primary: base.brand[600],
    'primary-foreground': base.white,
    secondary: base.slate[100],
    'secondary-foreground': base.slate[900],
    destructive: base.error,
    'destructive-foreground': base.white,
    'destructive-dark': base['error-dark'],
    success: base.success,
    'success-foreground': base.white,
    'success-subtle': base['success-subtle'],
    'success-dark': base['success-dark'],
    warning: base.warning,
    'warning-foreground': base.white,
    'warning-subtle': base['warning-subtle'],
    'warning-dark': base['warning-dark'],
    info: base.info,
    'info-foreground': base.white,
    'info-subtle': base['info-subtle'],
    'info-dark': base['info-dark'],
    muted: base.slate[100],
    'muted-foreground': base.slate[500],
    accent: base.slate[100],
    'accent-foreground': base.slate[900],
    border: base.slate[200],
    input: base.slate[200],
    // Primary interactive control color (buttons, links, prices)
    action: base.action,
    // Inverse surface (dark card in light mode context)
    'inverse-surface': base['inverse-surface'],
    'inverse-muted': base['inverse-muted'],
    'inverse-subtle': base['inverse-subtle'],
    // Overlay / modal scrim
    overlay: base.overlay,
  },
  dark: {
    background: base.slate[950],
    foreground: base.slate[50],
    card: base.slate[950],
    'card-foreground': base.slate[50],
    popover: base.slate[950],
    'popover-foreground': base.slate[50],
    primary: base.brand[500],
    'primary-foreground': base.slate[950],
    action: base.brand[500],
    secondary: base.slate[800],
    'secondary-foreground': base.slate[50],
    destructive: base.error,
    'destructive-foreground': base.slate[50],
    'destructive-dark': base['error-dark'],
    success: base.success,
    'success-foreground': base.slate[950],
    'success-subtle': base['success-subtle'],
    'success-dark': base['success-dark'],
    warning: base.warning,
    'warning-foreground': base.slate[950],
    'warning-subtle': base['warning-subtle'],
    'warning-dark': base['warning-dark'],
    info: base.info,
    'info-foreground': base.slate[950],
    'info-subtle': base['info-subtle'],
    'info-dark': base['info-dark'],
    muted: base.slate[800],
    'muted-foreground': base.slate[400],
    accent: base.slate[800],
    'accent-foreground': base.slate[50],
    border: base.slate[800],
    input: base.slate[800],
    ring: base.brand[500],
    'inverse-surface': base.slate[50],
    'inverse-muted': base.slate[400],
    'inverse-subtle': base.slate[300],
    overlay: 'rgba(2, 6, 23, 0.7)',
  }
};

export const colors = {
  base,
  semantic
};
