"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAX_AD_SPARE_PARTS = exports.MAX_AD_DESCRIPTION_CHARS = exports.MIN_AD_DESCRIPTION_CHARS = exports.MAX_AD_TITLE_CHARS = exports.MIN_AD_TITLE_CHARS = exports.MAX_AD_IMAGE_BYTES = exports.MAX_AD_IMAGES = exports.MIN_AD_IMAGES = exports.AD_LIMITS = void 0;
exports.AD_LIMITS = {
    MIN_IMAGES: 1,
    MAX_IMAGES: 6,
    MAX_IMAGE_BYTES: 5 * 1024 * 1024,
    MIN_TITLE_CHARS: 10,
    MAX_TITLE_CHARS: 60,
    MIN_DESCRIPTION_CHARS: 20,
    MAX_DESCRIPTION_CHARS: 500,
    MAX_SPARE_PARTS: 20,
};
exports.MIN_AD_IMAGES = exports.AD_LIMITS.MIN_IMAGES;
exports.MAX_AD_IMAGES = exports.AD_LIMITS.MAX_IMAGES;
exports.MAX_AD_IMAGE_BYTES = exports.AD_LIMITS.MAX_IMAGE_BYTES;
exports.MIN_AD_TITLE_CHARS = exports.AD_LIMITS.MIN_TITLE_CHARS;
exports.MAX_AD_TITLE_CHARS = exports.AD_LIMITS.MAX_TITLE_CHARS;
exports.MIN_AD_DESCRIPTION_CHARS = exports.AD_LIMITS.MIN_DESCRIPTION_CHARS;
exports.MAX_AD_DESCRIPTION_CHARS = exports.AD_LIMITS.MAX_DESCRIPTION_CHARS;
exports.MAX_AD_SPARE_PARTS = exports.AD_LIMITS.MAX_SPARE_PARTS;
//# sourceMappingURL=adLimits.js.map