export * from './utils/logger';
export * from './domains/entitlements';
export * from './services/MonetizationService';
export * from './models/AdvertisementCampaign';
export * from './domains/notifications';
export { computeInvoiceTax, type TaxCalculationResult } from '@esparex/contracts';
export { AppError } from './shared-kernel/errors/AppError';


// ─── P1-10: domain services (moved from domain barrels to avoid cycles) ───
export { approveCatalogRequest, markCatalogRequestDuplicate, rejectCatalogRequest } from './domains/catalog/application/requests/catalogRequestApprovalService';
export * from './domains/catalog/application/services/CatalogBrandModelService';
export * from './domains/catalog/application/services/CatalogCategoryService';
export * from './domains/catalog/application/services/CatalogHierarchyService';
export * from './domains/catalog/application/services/CatalogImportService';
export * from './domains/catalog/application/services/CatalogOrchestrator';
export * from './domains/catalog/application/services/CatalogReferenceService';
export * from './domains/catalog/application/services/CatalogRequestService';
export * from './domains/catalog/application/services/CatalogSearchGovernanceService';
export * from './domains/catalog/application/services/CatalogSeedService';
export * from './domains/catalog/application/services/CatalogSparePartService';
export * from './domains/catalog/application/services/CatalogValidationService';
export * from './domains/listings/application/ad/ad/AdMetricsService';
export * from './domains/listings/application/ad/AdOrchestrator';
export * from './domains/listings/application/ad/ad/_shared/adFilterHelpers';
export * from './domains/listings/application/aggregation/adAggregation/pipeline';
export * from './domains/listings/application/mutations/AdMutationService';
export * as AdMetricsService from './domains/listings/application/ad/ad/AdMetricsService';
// ─── P1-10: identity/payments services ───
export * from './domains/identity/application/users/UserStatusService';
export * from './domains/payments/application/DashboardFacade';
export * from './domains/payments/application/PlanService';

export * as AdminListingsService from './domains/listings/application/moderation/adminListings';
export * as AdOrchestrator from './domains/listings/application/ad/AdOrchestrator';
export * as AdMutationService from './domains/listings/application/mutations/AdMutationService';
export * as AdEngagementService from './domains/listings/application/ad/AdEngagementService';
export * as CatalogRequestService from './domains/catalog/application/services/CatalogRequestService';
export { getReportedAdsAggregation } from './domains/listings/application/ad/ad/AdDetailService';
export * as AdAggregationService from './domains/listings/application/ad/ad/AdAggregationService';
export * as AdDetailService from './domains/listings/application/ad/ad/AdDetailService';
export * from './domains/listings/application/aggregation/adAggregation/metadata';
export * from './domains/listings/application/saved/SavedAdService';

// ─── P1-10: documented public surface — consolidated re-exports (2026-10-07) ───
// Deep `@esparex/core/*` subpaths were removed from the exports map (DECISION-GATE P1-10).
// External consumers import from this root barrel or a `./domains/<name>` barrel.
// Side-effectful modules (env validation, model registry) are imported first.
import './config/loadEnv';
import './models/registry';
// Shared modules (star re-exports)
export * from './composition/catalog';
export * from './composition/listings';
export * from './config/constants';
export * from './config/db';
export * from './config/env';
export * from './config/featureFlags';
export * from './config/loadEnvFiles';
export * from './config/razorpay';
export * from './config/redis';
export * from './config/sentry';
export * from './config/socket';
export * from './config/validateEnv';
export * from './constants/adminPermissions';
export * from './db/indexAuditTargets';
export * from './db/indexGovernance';
export * from './events';
export * from './jobs/expiryWarning.job';
export * from './lib/location/formatLocation';
export * from './lib/redis';
export * from './migrations/catalogApprovalMigration';
export * from './models/Ad';
export * from './models/Admin';
export * from './models/AdminLog';
export * from './models/Business';
export * from './models/CatalogRequest';
export * from './models/Category';
export * from './models/FraudScore';
export * from './models/IdempotencyRequest';
export * from './models/Location';
export * from './models/Notification';
export * from './models/NotificationLog';
export * from './models/Report';
export * from './models/ScheduledNotification';
export * from './models/ServiceType';
export * from './models/StatusHistory';
export { GeoJSONPoint, type IUser } from './models/User';
export { default as User } from './models/User';
export * from './prompts/listings/v1';
export * from './queues/paymentQueue';
export * from './services/AdminBusinessService';
export * from './services/AdminDashboardService';
export * from './services/AdminService';
export * from './services/AiService';
export * from './services/ApiKeyService';
export * from './services/BulkImportService';
export * from './services/GoogleAdsService';
export * from './services/PageContentService';
export * from './services/SchedulerBoot';
export * from './services/SystemConfigService';
export * from './services/ai/AIProviderFactory';
export * from './services/business/BusinessCoreService';
export * from './services/business/BusinessLifecycleService';
export * from './services/business/BusinessSearchService';
export * from './services/lifecycle/ListingExpiryService';
export * from './services/lifecycle/StatusMutationService';
export * from './services/location/LocationEventService';
export * from './services/location/LocationHierarchyService';
export * from './services/location/LocationNormalizer';
export * from './services/location/LocationSearchService';
export * from './services/location/ReverseGeocodeService';
export * from './types/auth';
export * from './utils/FeedVisibilityGuard';
export * from './utils/adFilterHelper';
export * from './utils/adminLogger';
export * from './utils/aiEncryption';
export * from './utils/aiSpamDetector';
export * from './utils/appUrl';
export * from './utils/auth';
export * from './utils/businessHelpers';
export * from './utils/businessSerializer';
export * from './utils/businessStatus';
export * from './utils/cacheWarmer';
export * from './utils/catalogShadowRead';
export * from './utils/cookieHelper';
export * from './utils/distributedJobLock';
export * from './utils/errorHelpers';
export * from './utils/health';
export * from './utils/idUtils';
export * from './utils/imageProcessor';
export * from './utils/immutableFieldErrors';
export * from './utils/invoiceNumber';
export * from './utils/listingTypeIntegrity';
export * from './utils/metrics';
export * from './utils/mongoQueryValidator';
export * from './utils/originConfig';
export * from './utils/phoneUtils';
export * from './utils/redirectValidator';
export * from './utils/redisCache';
export * from './utils/reliabilityAlerts';
export * from './utils/reliabilityContext';
export * from './utils/resilience';
export * from './utils/roleNormalization';
export * from './utils/s3';
export * from './utils/securityMonitoring';
export * from './utils/serialize';
export * from './utils/shutdownHandler';
export * from './utils/sloMonitor';
export * from './utils/ssrfGuard';
export * from './utils/startupValidator';
export * from './utils/statusQueryMapper';
export * from './utils/stringUtils';
export * from './utils/systemConfigHelper';
export * from './utils/systemMetricsSummary';
export * from './utils/systemMonitor';
export * from './utils/uploadFactory';
export * from './validators/ad.validator';
export * from './validators/adminAudit.validator';
export * from './validators/adminModeration.validator';
export * from './validators/ai.validator';
export * from './validators/auth.validator';
export * from './validators/business.validator';
export * from './validators/catalog.validator';
export * from './validators/catalogRequest.validator';
export * from './validators/chat.validator';
export * from './validators/common';
export * from './validators/finance.validator';
export * from './validators/location.validator';
export * from './validators/report.validator';
export * from './validators/savedAd.validator';
export * from './validators/user.validator';
// Default-export aliases (star re-exports exclude `default`)
export { default as logger } from './utils/logger';
export { default as firebaseAdmin } from './config/firebaseAdmin';
export { default as bootstrapLogger } from './utils/bootstrapLogger';
export { default as redisClient } from './utils/redisCache';
export { default as Sentry } from './config/sentry';
export { default as Ad } from './models/Ad';
export { default as Admin } from './models/Admin';
export { default as AdminLog } from './models/AdminLog';
export { default as Business } from './models/Business';
export { default as CatalogRequest } from './models/CatalogRequest';
export { default as Category } from './models/Category';
export { default as FraudScore } from './models/FraudScore';
export { default as IdempotencyRequest } from './models/IdempotencyRequest';
export { default as Location } from './models/Location';
export { default as Notification } from './models/Notification';
export { default as NotificationLog } from './models/NotificationLog';
export { default as Report } from './models/Report';
export { default as ScheduledNotification } from './models/ScheduledNotification';
export { default as ServiceType } from './models/ServiceType';
export { default as StatusHistory } from './models/StatusHistory';
// Explicit named-export lists (module has both named `X` and `export default X`)
export { type IModel } from './models/Model';
export { default as Model } from './models/Model';
export { type ISparePart } from './models/SparePart';
export { default as SparePart } from './models/SparePart';
export { CategoryFieldType, type CategoryQueryInput } from './utils/CategoryQueryBuilder';
export { default as CategoryQueryBuilder } from './utils/CategoryQueryBuilder';
// Explicit resolutions for star-export name collisions (canonical per consumer usage)
export { normalizeBusinessStatus } from './utils/businessStatus';
export { normalizeLocation } from './services/location/LocationNormalizer';
export { shouldDisableRedis } from './config/redis';
export { isTimeoutError } from './utils/errorHelpers';
export { isNetworkError } from './utils/errorHelpers';
export { normalizeObjectIdLike } from './utils/idUtils';
export { normalizeGeoPoint, normalizeCoordinates } from './services/location/_shared/locationServiceBase';

export * from './workers';
