import { LIFECYCLE_STATUS, type ListingStatus } from '@esparex/contracts';

/**
 * Ad Lifecycle State Machine (SSOT)
 * Validates legal status transitions across all domain entities (Ad, User, Business, Service, SparePart).
 */
export const ALLOWED_AD_TRANSITIONS: Record<string, string[]> = {
    [LIFECYCLE_STATUS.DRAFT]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.PENDING]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.REJECTED, LIFECYCLE_STATUS.DEACTIVATED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.LIVE]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.REJECTED, LIFECYCLE_STATUS.SOLD, LIFECYCLE_STATUS.EXPIRED, LIFECYCLE_STATUS.DEACTIVATED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.SOLD]: [LIFECYCLE_STATUS.DEACTIVATED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.EXPIRED]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.SOLD, LIFECYCLE_STATUS.DEACTIVATED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.REJECTED]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.DEACTIVATED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.DEACTIVATED]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.DELETED]: [],
    [LIFECYCLE_STATUS.ACTIVE]: [LIFECYCLE_STATUS.DEACTIVATED, LIFECYCLE_STATUS.SOLD, LIFECYCLE_STATUS.EXPIRED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.SUSPENDED]: [LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.BANNED]: [LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.CLOSED]: [LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.INACTIVE]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.DELETED],
};

export const ALLOWED_USER_TRANSITIONS: Record<string, string[]> = {
    [LIFECYCLE_STATUS.LIVE]: [LIFECYCLE_STATUS.SUSPENDED, LIFECYCLE_STATUS.BANNED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.SUSPENDED]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.BANNED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.BANNED]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.INACTIVE]: [LIFECYCLE_STATUS.LIVE],
    [LIFECYCLE_STATUS.DELETED]: [],
};

export const ALLOWED_BUSINESS_TRANSITIONS: Record<string, string[]> = {
    [LIFECYCLE_STATUS.PENDING]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.REJECTED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.LIVE]: [
        LIFECYCLE_STATUS.PENDING,
        LIFECYCLE_STATUS.SUSPENDED, 
        LIFECYCLE_STATUS.EXPIRED, 
        LIFECYCLE_STATUS.DEACTIVATED, 
        LIFECYCLE_STATUS.SOLD,
        LIFECYCLE_STATUS.DELETED
    ],
    [LIFECYCLE_STATUS.REJECTED]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.SUSPENDED]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.EXPIRED]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.DEACTIVATED]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.SOLD]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.DELETED]: [],
};

export const ALLOWED_SERVICE_TRANSITIONS: Record<string, string[]> = {
    [LIFECYCLE_STATUS.PENDING]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.REJECTED],
    [LIFECYCLE_STATUS.LIVE]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.SOLD, LIFECYCLE_STATUS.EXPIRED, LIFECYCLE_STATUS.DEACTIVATED],
    [LIFECYCLE_STATUS.SOLD]: [LIFECYCLE_STATUS.DEACTIVATED, LIFECYCLE_STATUS.DELETED],
    [LIFECYCLE_STATUS.REJECTED]: [LIFECYCLE_STATUS.PENDING],
    [LIFECYCLE_STATUS.EXPIRED]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.LIVE],
    [LIFECYCLE_STATUS.DEACTIVATED]: [LIFECYCLE_STATUS.LIVE],
};

export const ALLOWED_SPARE_PART_LISTING_TRANSITIONS: Record<string, string[]> = {
    [LIFECYCLE_STATUS.PENDING]: [LIFECYCLE_STATUS.LIVE, LIFECYCLE_STATUS.REJECTED],
    [LIFECYCLE_STATUS.LIVE]: [LIFECYCLE_STATUS.SOLD, LIFECYCLE_STATUS.EXPIRED, LIFECYCLE_STATUS.DEACTIVATED],
    [LIFECYCLE_STATUS.REJECTED]: [LIFECYCLE_STATUS.PENDING],
    [LIFECYCLE_STATUS.EXPIRED]: [LIFECYCLE_STATUS.PENDING, LIFECYCLE_STATUS.LIVE],
    [LIFECYCLE_STATUS.DEACTIVATED]: [LIFECYCLE_STATUS.LIVE],
    [LIFECYCLE_STATUS.SOLD]: [LIFECYCLE_STATUS.DELETED],
};

export const canTransitionAdStatus = (from: ListingStatus | string, to: ListingStatus | string): boolean => {
    if (from === to) return true;
    const allowed = ALLOWED_AD_TRANSITIONS[from];
    return Array.isArray(allowed) && allowed.includes(to);
};
