import { LISTING_STATUS, type ListingStatus } from '@esparex/contracts';

/**
 * Ad Lifecycle State Machine (SSOT)
 * Validates legal status transitions for Ads/Listings to enforce domain invariants.
 */
const LEGAL_AD_TRANSITIONS: Record<string, readonly string[]> = {
    [LISTING_STATUS.DRAFT]: [LISTING_STATUS.PENDING, LISTING_STATUS.DELETED],
    [LISTING_STATUS.PENDING]: [LISTING_STATUS.LIVE, LISTING_STATUS.REJECTED, LISTING_STATUS.DELETED],
    [LISTING_STATUS.LIVE]: [LISTING_STATUS.DEACTIVATED, LISTING_STATUS.SOLD, LISTING_STATUS.EXPIRED, LISTING_STATUS.DELETED],
    [LISTING_STATUS.DEACTIVATED]: [LISTING_STATUS.LIVE, LISTING_STATUS.DELETED],
    [LISTING_STATUS.EXPIRED]: [LISTING_STATUS.LIVE, LISTING_STATUS.DELETED],
    [LISTING_STATUS.REJECTED]: [LISTING_STATUS.DELETED],
    [LISTING_STATUS.SOLD]: [LISTING_STATUS.DELETED],
    [LISTING_STATUS.DELETED]: [],
    [LISTING_STATUS.ACTIVE]: [LISTING_STATUS.DEACTIVATED, LISTING_STATUS.SOLD, LISTING_STATUS.EXPIRED, LISTING_STATUS.DELETED],
    [LISTING_STATUS.SUSPENDED]: [LISTING_STATUS.DELETED],
    [LISTING_STATUS.BANNED]: [LISTING_STATUS.DELETED],
    [LISTING_STATUS.CLOSED]: [LISTING_STATUS.DELETED],
    [LISTING_STATUS.INACTIVE]: [LISTING_STATUS.LIVE, LISTING_STATUS.DELETED],
};

export const canTransitionAdStatus = (from: ListingStatus, to: ListingStatus): boolean => {
    if (from === to) return true;
    const allowed = LEGAL_AD_TRANSITIONS[from];
    return Array.isArray(allowed) && allowed.includes(to);
};
