/**
 * boundaries-config.js
 * =====================
 * AUTO-GENERATED — DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/architecture/generate-eslint-boundaries.js
 * Source of truth: scripts/architecture/matrix.js
 * Architecture Version: v1.1.0
 * Generated: 2026-07-08T03:27:00.207Z
 *
 * To regenerate:
 *   node scripts/architecture/generate-eslint-boundaries.js
 */

'use strict';

/** @type {{ elements: object[], rules: object[] }} */
module.exports = {
  "elements": [
    {
      "type": "apps-web",
      "pattern": "apps/web/src/**"
    },
    {
      "type": "apps-admin",
      "pattern": "apps/admin/src/**"
    },
    {
      "type": "backend",
      "pattern": "backend/user/src/**"
    },
    {
      "type": "core",
      "pattern": "core/src/**"
    },
    {
      "type": "shared",
      "pattern": "shared/src/**"
    },
    {
      "type": "core-types",
      "pattern": "core/src/types/**"
    },
    {
      "type": "core-config",
      "pattern": "core/src/config/**"
    },
    {
      "type": "core-domain",
      "pattern": "core/src/domain/**"
    },
    {
      "type": "core-utils",
      "pattern": "core/src/utils/**"
    },
    {
      "type": "core-validators",
      "pattern": "core/src/validators/**"
    },
    {
      "type": "core-events",
      "pattern": "core/src/events/**"
    },
    {
      "type": "core-models",
      "pattern": "core/src/models/**"
    },
    {
      "type": "core-infrastructure",
      "pattern": "core/src/infrastructure/**"
    },
    {
      "type": "core-tooling",
      "pattern": "core/src/tooling/**"
    },
    {
      "type": "core-services",
      "pattern": "core/src/services/**"
    },
    {
      "type": "core-queues",
      "pattern": "core/src/queues/**"
    },
    {
      "type": "core-jobs",
      "pattern": "core/src/jobs/**"
    },
    {
      "type": "core-workers",
      "pattern": "core/src/workers/**"
    }
  ],
  "rules": [
    {
      "message": "Apps may only import shared and core public types/domain",
      "from": [
        {
          "type": "apps-web"
        },
        {
          "type": "apps-admin"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "shared"
          }
        },
        {
          "to": {
            "type": "core-types"
          }
        },
        {
          "to": {
            "type": "core-domain"
          }
        }
      ]
    },
    {
      "message": "Backend may import any public @esparex/core namespace but not core internals",
      "from": [
        {
          "type": "backend"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "shared"
          }
        },
        {
          "to": {
            "type": "core"
          }
        }
      ]
    },
    {
      "message": "Core may import shared only (no backend or apps)",
      "from": [
        {
          "type": "core"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "shared"
          }
        }
      ]
    },
    {
      "message": "Shared is fully isolated",
      "from": [
        {
          "type": "shared"
        }
      ],
      "allow": []
    },
    {
      "message": "[Matrix] Core Domain allowed dependencies",
      "from": [
        {
          "type": "core-domain"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-types"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Utils allowed dependencies",
      "from": [
        {
          "type": "core-utils"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-types"
          }
        },
        {
          "to": {
            "type": "core-config"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Validators allowed dependencies",
      "from": [
        {
          "type": "core-validators"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-types"
          }
        },
        {
          "to": {
            "type": "core-domain"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Events allowed dependencies",
      "from": [
        {
          "type": "core-events"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-domain"
          }
        },
        {
          "to": {
            "type": "core-types"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Models allowed dependencies",
      "from": [
        {
          "type": "core-models"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-domain"
          }
        },
        {
          "to": {
            "type": "core-types"
          }
        },
        {
          "to": {
            "type": "core-config"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Infrastructure allowed dependencies",
      "from": [
        {
          "type": "core-infrastructure"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-config"
          }
        },
        {
          "to": {
            "type": "core-utils"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Tooling allowed dependencies",
      "from": [
        {
          "type": "core-tooling"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-infrastructure"
          }
        },
        {
          "to": {
            "type": "core-config"
          }
        },
        {
          "to": {
            "type": "core-utils"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Services allowed dependencies",
      "from": [
        {
          "type": "core-services"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-models"
          }
        },
        {
          "to": {
            "type": "core-domain"
          }
        },
        {
          "to": {
            "type": "core-validators"
          }
        },
        {
          "to": {
            "type": "core-utils"
          }
        },
        {
          "to": {
            "type": "core-events"
          }
        },
        {
          "to": {
            "type": "core-infrastructure"
          }
        },
        {
          "to": {
            "type": "core-config"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Queues allowed dependencies",
      "from": [
        {
          "type": "core-queues"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-infrastructure"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Jobs allowed dependencies",
      "from": [
        {
          "type": "core-jobs"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-services"
          }
        },
        {
          "to": {
            "type": "core-infrastructure"
          }
        }
      ]
    },
    {
      "message": "[Matrix] Core Workers allowed dependencies",
      "from": [
        {
          "type": "core-workers"
        }
      ],
      "allow": [
        {
          "to": {
            "type": "core-queues"
          }
        },
        {
          "to": {
            "type": "core-services"
          }
        }
      ]
    }
  ]
};
