export enum AiErrorCode {
    AI_QUOTA_EXHAUSTED = 'AI_QUOTA_EXHAUSTED',
    AI_UNAVAILABLE = 'AI_UNAVAILABLE',
    AI_INVALID_API_KEY = 'AI_INVALID_API_KEY',
    AI_PROVIDER_TIMEOUT = 'AI_PROVIDER_TIMEOUT',
    AI_INVALID_JSON = 'AI_INVALID_JSON',
    AI_CONFIG_MISSING = 'AI_CONFIG_MISSING',
    AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',
    AI_UNKNOWN_ERROR = 'AI_UNKNOWN_ERROR'
}
