/**
 * Single Source of Truth (SSOT) Error Code Enum for Esparex Platform
 */
export enum BusinessErrorCode {
  // Authentication & Identity
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_OTP = 'AUTH_INVALID_OTP',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS = 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Listings & Post Ad
  DUPLICATE_AD = 'DUPLICATE_AD',
  LISTING_NOT_FOUND = 'LISTING_NOT_FOUND',
  LISTING_LIMIT_EXCEEDED = 'LISTING_LIMIT_EXCEEDED',
  INVALID_CATEGORY_ATTRIBUTES = 'INVALID_CATEGORY_ATTRIBUTES',
  IMAGE_CATEGORY_MISMATCH = 'IMAGE_CATEGORY_MISMATCH',
  IMAGE_MODERATION_FAILED = 'IMAGE_MODERATION_FAILED',

  // Payments & Subscriptions
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_ALREADY_COMPLETED = 'PAYMENT_ALREADY_COMPLETED',
  PLAN_EXPIRED = 'PLAN_EXPIRED',
  QUOTA_EXHAUSTED = 'QUOTA_EXHAUSTED',

  // Security & Fraud
  FRAUD_DETECTED = 'FRAUD_DETECTED',
  SPAM_DETECTED = 'SPAM_DETECTED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',

  // General & Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
