import { Reporter, GovernanceSummaryReport } from "../types/index.js";
import * as fs from "fs";

export class MarkdownReporter implements Reporter {
  id = "markdown-reporter";
  name = "Markdown Governance Report";

  async write(report: GovernanceSummaryReport, options: Record<string, any>): Promise<void> {
    const outPath = options.outputPath || "./governance-report.md";

    const lines: string[] = [
      "# Governance Report",
      "",
      `**Generated:** ${new Date(report.timestamp).toISOString()}`,
      `**Schema:** v${report.schemaVersion}`,
      "",
      "---",
      "",
      "## Overall Health",
      "",
      `**Score:** ${report.overallScore}/100`,
      "",
      "## Summary",
      "",
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Analyzers | ${report.results.length} |`,
      `| Passed | ${report.results.filter(r => r.passed).length} |`,
      `| Failed | ${report.results.filter(r => !r.passed).length} |`,
      `| Total Violations | ${report.results.reduce((s, r) => s + r.violationsCount, 0)} |`,
      "",
      "## Per-Analyzer Results",
      "",
      `| Analyzer | Score | Violations | Status |`,
      `|----------|-------|-----------|--------|`,
    ];

    for (const r of report.results) {
      lines.push(`| ${r.name} | ${r.score}/100 | ${r.violationsCount} | ${r.passed ? "✅ PASS" : "❌ FAIL"} |`);
    }

    const failedWithViolations = report.results.filter(r => !r.passed && r.report.violations.length > 0);
    if (failedWithViolations.length > 0) {
      lines.push("", "## Violations", "");
      for (const r of failedWithViolations) {
        lines.push(`### ${r.name}`);
        lines.push("");
        lines.push(`| Severity | Rule | Message | File |`);
        lines.push(`|----------|------|---------|------|`);
        for (const v of r.report.violations) {
          const fileRef = v.file ? `${v.file}${v.line ? `:${v.line}` : ""}` : "-";
          lines.push(`| ${v.severity} | \`${v.ruleId}\` | ${v.message} | ${fileRef} |`);
        }
        lines.push("");
      }
    }

    lines.push("---");
    lines.push("");
    lines.push("_Generated by @esparex/repository-governance_");

    fs.writeFileSync(outPath, lines.join("\n"), "utf-8");
  }
}
